In [1]:
pip install sympy

In [3]:
from sympy import *

In [4]:
M = Matrix(([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]))
M 

Matrix([
[ 1,  2,  3,  4],
[ 5,  6,  7,  8],
[ 9, 10, 11, 12],
[13, 14, 15, 16]])

In [5]:
A = Matrix([[1,1,1],[1,1,3],[2,3,4]])
Q, R = A.QRdecomposition()
Q

Matrix([
[sqrt(6)/6, -sqrt(3)/3, -sqrt(2)/2],
[sqrt(6)/6, -sqrt(3)/3,  sqrt(2)/2],
[sqrt(6)/3,  sqrt(3)/3,          0]])

In [6]:
R

Matrix([
[sqrt(6), 4*sqrt(6)/3, 2*sqrt(6)],
[      0,   sqrt(3)/3,         0],
[      0,           0,   sqrt(2)]])

In [7]:
Q*R

Matrix([
[1, 1, 1],
[1, 1, 3],
[2, 3, 4]])

In [8]:
A = Matrix([ [2, 3, 5], [3, 6, 2], [8, 3, 6] ])
x = Matrix(3,1,[3,7,5])
b = A*x
soln = A.LUsolve(b)
soln

Matrix([
[3],
[7],
[5]])

In [9]:
L = [Matrix([2,3,5]), Matrix([3,6,2]), Matrix([8,3,6])]
out1 = GramSchmidt(L)
out2 = GramSchmidt(L, True)

In [10]:
out1

[Matrix([
 [2],
 [3],
 [5]]), Matrix([
 [ 23/19],
 [ 63/19],
 [-47/19]]), Matrix([
 [ 1692/353],
 [-1551/706],
 [ -423/706]])]

In [11]:
out2

[Matrix([
 [  sqrt(38)/19],
 [3*sqrt(38)/38],
 [5*sqrt(38)/38]]), Matrix([
 [ 23*sqrt(6707)/6707],
 [ 63*sqrt(6707)/6707],
 [-47*sqrt(6707)/6707]]), Matrix([
 [ 12*sqrt(706)/353],
 [-11*sqrt(706)/706],
 [ -3*sqrt(706)/706]])]

In [12]:
M = Matrix([[1, 2], [3, 4]])
M.cofactor(0, 1)

-3

In [13]:
M.cofactor_matrix()

Matrix([
[ 4, -3],
[-2,  1]])

In [14]:
M = Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
M.minor(1, 1)

-12

In [16]:
M.minor_submatrix(1, 1)

Matrix([
[1, 3],
[7, 9]])

In [17]:
M = Matrix([[1, 2], [3, 4]])
M.echelon_form()

Matrix([
[1,  2],
[0, -2]])

In [18]:
n = Matrix(3, 3, range(1, 10))
n.rank()

2

In [20]:
from sympy.abc import x
m = Matrix([[1, 2], [x, 1 - 1/x]])
m.rref()

(Matrix([
 [1, 0],
 [0, 1]]), (0, 1))

In [21]:
rref_matrix, rref_pivots = m.rref()
rref_matrix

Matrix([
[1, 0],
[0, 1]])

In [22]:
rref_pivots

(0, 1)

In [23]:
M = Matrix(3, 3, [1, 3, 0, -2, -6, 0, 3, 9, 6])
M

Matrix([
[ 1,  3, 0],
[-2, -6, 0],
[ 3,  9, 6]])

In [24]:
M.columnspace()

[Matrix([
 [ 1],
 [-2],
 [ 3]]), Matrix([
 [0],
 [0],
 [6]])]

In [25]:
M = Matrix(3, 3, [1, 3, 0, -2, -6, 0, 3, 9, 6])
M

Matrix([
[ 1,  3, 0],
[-2, -6, 0],
[ 3,  9, 6]])

In [26]:
M.rowspace()

[Matrix([[1, 3, 0]]), Matrix([[0, 0, 6]])]

In [27]:
M = Matrix(3, 3, [1, 3, 0, -2, -6, 0, 3, 9, 6])
M

Matrix([
[ 1,  3, 0],
[-2, -6, 0],
[ 3,  9, 6]])

In [28]:
M.nullspace()

[Matrix([
 [-3],
 [ 1],
 [ 0]])]

In [29]:
v = [Matrix([1, I]), Matrix([1, -I])]
Matrix.orthogonalize(*v)

[Matrix([
 [1],
 [I]]), Matrix([
 [zoo],
 [zoo]])]

In [33]:
A = Matrix([[1, 0], [0, 1]])
#A.is_positive_definite

In [34]:
#A.is_positive_semidefinite

In [35]:
from numpy import array
from scipy.linalg import svd
# Singular Value Decomposition - SVD
A = array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [38]:
U, s, VT = svd(A)
print(U)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]


In [39]:
print(s)

[9.52551809 0.51430058]


In [40]:
print(VT)

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [42]:
import numpy as np
from sklearn.decomposition import PCA
# Principal Component Analysis - PCA  
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
pca = PCA(n_components=2)
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [43]:
print(pca.explained_variance_ratio_)

[0.99244289 0.00755711]


In [44]:
print(pca.singular_values_)

[6.30061232 0.54980396]
