In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
a = np.array([1,3,-2,1])
print(a)

[ 1  3 -2  1]


In [3]:
a.ndim

1

In [4]:
a.shape

(4,)

In [5]:
a.size

4

In [6]:
M = np.array([[1,2],[3,7],[-1,5]])
print(M)

[[ 1  2]
 [ 3  7]
 [-1  5]]


In [7]:
M.ndim

2

In [8]:
M.shape

(3, 2)

In [9]:
M.size

6

In [10]:
col = M[:,1] 
print(col)

[2 7 5]


In [11]:
col.ndim

1

In [12]:
col.shape

(3,)

In [13]:
col.size

3

In [15]:
print(col)

[2 7 5]


In [14]:
column = np.array([2,7,5]).reshape(3,1)
print(column)

[[2]
 [7]
 [5]]


In [16]:
print('Dimensions:', column.ndim)
print('Shape:', column.shape)
print('Size:', column.size)

Dimensions: 2
Shape: (3, 1)
Size: 3


In [17]:
print('Dimensions:',col.ndim)
print('Shape:',col.shape)
print('Size:',col.size)

Dimensions: 1
Shape: (3,)
Size: 3


In [18]:
M = np.array([[3,4],[-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


In [19]:
M * M

array([[ 9, 16],
       [ 1, 25]])

In [20]:
M @ M

array([[ 5, 32],
       [-8, 21]])

In [21]:
A = np.array([[1,3],[-1,7]])
print(A)

B = np.array([[5,2],[1,2]])
print(B)

I = np.eye(2)
print(I)

[[ 1  3]
 [-1  7]]
[[5 2]
 [1 2]]
[[1. 0.]
 [0. 1.]]


In [22]:
2*I + 3*A - A@B

array([[-3.,  1.],
       [-5., 11.]])

In [23]:
from numpy.linalg import matrix_power as mpow

In [24]:
M = np.array([[3,4],[-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


In [25]:
mpow(M,2)

array([[ 5, 32],
       [-8, 21]])

In [26]:
mpow(M,5)

array([[-1525,  3236],
       [ -809,    93]])

In [27]:
M @ M @ M @ M @ M

array([[-1525,  3236],
       [ -809,    93]])

In [28]:
mpow(M,3)

array([[-17, 180],
       [-45,  73]])

In [29]:
mpow(M,3)

array([[-17, 180],
       [-45,  73]])

In [30]:
print(M)

[[ 3  4]
 [-1  5]]


In [31]:
print(M.T)

[[ 3 -1]
 [ 4  5]]


In [32]:
M @ M.T

array([[25, 17],
       [17, 26]])

In [33]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [34]:
la.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [35]:
np.trace(A)

5

In [36]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [37]:
la.det(A)

-2.0

In [38]:
print(A)

[[1 2]
 [3 4]]


In [39]:
trace_A = np.trace(A)
det_A = la.det(A)
I = np.eye(2)
A @ A - trace_A * A + det_A * I

array([[0., 0.],
       [0., 0.]])

In [40]:
N = np.random.randint(0,10,[2,2])
print(N)

trace_N = np.trace(N)
det_N = la.det(N)
I = np.eye(2)
N @ N - trace_N * N + det_N * I

[[9 0]
 [1 9]]


array([[0., 0.],
       [0., 0.]])

In [41]:
def proj(v,w):
    '''Project vector v onto w.'''
    v = np.array(v)
    w = np.array(w)
    return np.sum(v * w)/np.sum(w * w) * w   # or (v @ w)/(w @ w) * w

In [42]:
proj([1,2,3],[1,1,1])

array([2., 2., 2.])

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [43]:
A = np.array([[1,1,2],[-1,3,1],[0,5,2]])
print(A)

[[ 1  1  2]
 [-1  3  1]
 [ 0  5  2]]


In [44]:
E1 = np.array([[1,0,3],[0,1,0],[0,0,1]])
print(E1)

[[1 0 3]
 [0 1 0]
 [0 0 1]]


In [45]:
E1 @ A

array([[ 1, 16,  8],
       [-1,  3,  1],
       [ 0,  5,  2]])

In [46]:
E2 = np.array([[1,0,0],[0,-2,0],[0,0,1]])
print(E2)

[[ 1  0  0]
 [ 0 -2  0]
 [ 0  0  1]]


In [47]:
E2 @ A

array([[ 1,  1,  2],
       [ 2, -6, -2],
       [ 0,  5,  2]])

In [48]:
E3 = np.array([[1,0,0],[0,0,1],[0,1,0]])
print(E3)

[[1 0 0]
 [0 0 1]
 [0 1 0]]


In [49]:
E3 @ A

array([[ 1,  1,  2],
       [ 0,  5,  2],
       [-1,  3,  1]])

In [50]:
def add_row(A,k,i,j):
    "Add k times row j to row i in matrix A."
    n = A.shape[0]
    E = np.eye(n)
    if i == j:
        E[i,i] = k + 1
    else:
        E[i,j] = k
    return E @ A

In [51]:
M = np.array([[1,1],[3,2]])
print(M)

[[1 1]
 [3 2]]


In [52]:
add_row(M,2,0,1)

array([[7., 5.],
       [3., 2.]])

In [53]:
add_row(M,3,1,1)

array([[ 1.,  1.],
       [12.,  8.]])

In [54]:
def scale_row(A,k,i):
    "Multiply row i by k in matrix A."
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = k
    return E @ A

In [55]:
M = np.array([[3,1],[-2,7]])
print(M)

[[ 3  1]
 [-2  7]]


In [56]:
scale_row(M,3,1)

array([[ 3.,  1.],
       [-6., 21.]])

In [57]:
A = np.array([[1,1,1],[1,-1,0]])
print(A)

[[ 1  1  1]
 [ 1 -1  0]]


In [58]:
scale_row(A,5,1)

array([[ 1.,  1.,  1.],
       [ 5., -5.,  0.]])

In [59]:
def switch_rows(A,i,j):
    "Switch rows i and j in matrix A."
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = 0
    E[j,j] = 0
    E[i,j] = 1
    E[j,i] = 1
    return E @ A

In [60]:
A = np.array([[1,1,1],[1,-1,0]])
print(A)
switch_rows(A,0,1)

[[ 1  1  1]
 [ 1 -1  0]]


array([[ 1., -1.,  0.],
       [ 1.,  1.,  1.]])

In [62]:
M = np.array([[5,4,2],[-1,2,1],[1,1,1]])
print(M)

A = np.hstack([M,np.eye(3)])
print(A)

A1 = switch_rows(A,0,2)
print(A1)

A2 = add_row(A1,1,1,0)
print(A2)

A3 = add_row(A2,-5,2,0)
print(A3)

A4 = switch_rows(A3,1,2)
print(A4)

A5 = scale_row(A4,-1,1)
print(A5)

A6 = add_row(A5,-3,2,1)
print(A6)

A7 = scale_row(A6,-1/7,2)
print(A7)

A8 = add_row(A7,-3,1,2)
print(A8)

A9 = add_row(A8,-1,0,2)
print(A9)

A10 = add_row(A9,-1,0,1)
print(A10)


[[ 5  4  2]
 [-1  2  1]
 [ 1  1  1]]
[[ 5.  4.  2.  1.  0.  0.]
 [-1.  2.  1.  0.  1.  0.]
 [ 1.  1.  1.  0.  0.  1.]]
[[ 1.  1.  1.  0.  0.  1.]
 [-1.  2.  1.  0.  1.  0.]
 [ 5.  4.  2.  1.  0.  0.]]
[[1. 1. 1. 0. 0. 1.]
 [0. 3. 2. 0. 1. 1.]
 [5. 4. 2. 1. 0. 0.]]
[[ 1.  1.  1.  0.  0.  1.]
 [ 0.  3.  2.  0.  1.  1.]
 [ 0. -1. -3.  1.  0. -5.]]
[[ 1.  1.  1.  0.  0.  1.]
 [ 0. -1. -3.  1.  0. -5.]
 [ 0.  3.  2.  0.  1.  1.]]
[[ 1.  1.  1.  0.  0.  1.]
 [ 0.  1.  3. -1.  0.  5.]
 [ 0.  3.  2.  0.  1.  1.]]
[[  1.   1.   1.   0.   0.   1.]
 [  0.   1.   3.  -1.   0.   5.]
 [  0.   0.  -7.   3.   1. -14.]]
[[ 1.          1.          1.          0.          0.          1.        ]
 [ 0.          1.          3.         -1.          0.          5.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]
[[ 1.          1.          1.          0.          0.          1.        ]
 [ 0.          1.          0.          0.28571429  0.42857143 -1.        ]
 [ 0.        

In [64]:
Minv = A10[:,3:]
print(Minv)

[[ 0.14285714 -0.28571429  0.        ]
 [ 0.28571429  0.42857143 -1.        ]
 [-0.42857143 -0.14285714  2.        ]]


In [65]:
result = Minv @ M
print(result)

[[ 1.00000000e+00  2.22044605e-16  1.11022302e-16]
 [-4.44089210e-16  1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [66]:
np.round(result,15)

array([[ 1.,  0.,  0.],
       [-0.,  1., -0.],
       [ 0.,  0.,  1.]])

In [67]:
A = np.array([[6,15,1],[8,7,12],[2,7,8]])
print(A)

[[ 6 15  1]
 [ 8  7 12]
 [ 2  7  8]]


In [68]:
b = np.array([[2],[14],[10]])
print(b)

[[ 2]
 [14]
 [10]]


In [69]:
M = np.hstack([A,b])
print(M)

[[ 6 15  1  2]
 [ 8  7 12 14]
 [ 2  7  8 10]]


In [71]:
M1 = scale_row(M,1/6,0)
print(M1)

M2 = add_row(M1,-8,1,0)
print(M2)

M3 = add_row(M2,-2,2,0)
print(M3)

M4 = scale_row(M3,-1/13,1)
print(M4)

M5 = add_row(M4,-2,2,1)
print(M5)

M6 = scale_row(M5,1/M5[2,2],2)
print(M6)

M7 = add_row(M6,-M6[1,2],1,2)
print(M7)

M8 = add_row(M7,-M7[0,2],0,2)
print(M8)

M9 = add_row(M8,-M8[0,1],0,1)
print(M9)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 8.          7.         12.         14.        ]
 [ 2.          7.          8.         10.        ]]
[[  1.           2.5          0.16666667   0.33333333]
 [  0.         -13.          10.66666667  11.33333333]
 [  2.           7.           8.          10.        ]]
[[  1.           2.5          0.16666667   0.33333333]
 [  0.         -13.          10.66666667  11.33333333]
 [  0.           2.           7.66666667   9.33333333]]
[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          2.          7.66666667  9.33333333]]
[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          0.          9.30769231 11.07692308]]
[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          0.          1.          1.19008264]]
[[1.         2.5        0.16666667 0.33333333]
 [0. 

In [72]:
x = M9[:,3].reshape(3,1)
print(x)

[[-0.12672176]
 [ 0.1046832 ]
 [ 1.19008264]]


In [73]:
x = la.solve(A,b)
print(x)

[[-0.12672176]
 [ 0.1046832 ]
 [ 1.19008264]]


In [74]:
A = np.array([[1,1],[1,-1]])
print(A)

[[ 1  1]
 [ 1 -1]]


In [75]:
b1 = np.array([2,0])
print(b1)

[2 0]


In [76]:
x1 = la.solve(A,b1)
print(x1)

[1. 1.]


In [77]:
A = np.array([[1,1],[1,-1]])
b2 = np.array([2,0]).reshape(2,1)
x2 = la.solve(A,b2)
print(x2)

[[1.]
 [1.]]


In [78]:
A = np.array([[1,1],[1,-1]])
b3 = np.array([[2,2],[0,1]])
x3 = la.solve(A,b3)
print(x3)

[[1.  1.5]
 [1.  0.5]]


In [80]:
A = np.array([[2,1],[1,1]])
print(A)

b = np.array([1,-1]).reshape(2,1)
print(b)

[[2 1]
 [1 1]]
[[ 1]
 [-1]]


In [81]:
x = la.solve(A,b)
print(x)

[[ 2.]
 [-3.]]


In [82]:
Ainv = la.inv(A)
print(Ainv)

[[ 1. -1.]
 [-1.  2.]]


In [83]:
x = Ainv @ b
print(x)

[[ 2.]
 [-3.]]


In [84]:
N = 1000
A = np.random.rand(N,N)
b = np.random.rand(N,1)

In [85]:
A[:3,:3]

array([[0.40170312, 0.70506577, 0.48633674],
       [0.03902503, 0.56613817, 0.9400331 ],
       [0.76412985, 0.24851755, 0.58392342]])

In [86]:
b[:4,:]

array([[0.77797879],
       [0.73689911],
       [0.86765727],
       [0.02648667]])

In [88]:
%%timeit
x = la.solve(A,b)

10 loops, best of 3: 44.5 ms per loop


In [89]:
%%timeit
x = la.inv(A) @ b

10 loops, best of 3: 146 ms per loop
