In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

In [2]:
A = np.array([[1,0],[0,-2]])
print(A)

[[ 1  0]
 [ 0 -2]]


In [3]:
results = la.eig(A)

In [4]:
print(results[0])

[ 1.+0.j -2.+0.j]


In [5]:
print(results[1])

[[1. 0.]
 [0. 1.]]


In [6]:
eigvals, eigvecs = la.eig(A)
print(eigvals)

[ 1.+0.j -2.+0.j]


In [7]:
print(eigvecs)

[[1. 0.]
 [0. 1.]]


In [8]:
eigvals = eigvals.real
print(eigvals)

[ 1. -2.]


In [9]:
lambda1 = eigvals[1]
print(lambda1)

-2.0


In [10]:
v1 = eigvecs[:,1].reshape(2,1)
print(v1)

[[0.]
 [1.]]


In [12]:
A @ v1

array([[ 0.],
       [-2.]])

In [13]:
lambda1 * v1

array([[-0.],
       [-2.]])

In [14]:
n = 4
P = np.random.randint(0,10,(n,n))
print(P)

[[2 4 4 9]
 [1 3 6 9]
 [0 7 7 1]
 [5 9 3 0]]


In [15]:
S = P @ P.T
print(S)

[[117 119  65  58]
 [119 127  72  50]
 [ 65  72  99  84]
 [ 58  50  84 115]]


In [16]:
evals, evecs = la.eig(S)
print(evals)

[341.18572196+0.j  94.55868962+0.j   0.467078  +0.j  21.78851042+0.j]


In [17]:
evals = evals.real
print(evals)

[341.18572196  94.55868962   0.467078    21.78851042]


In [18]:
print(evecs)

[[ 0.54043062  0.39371868  0.6623461   0.33796153]
 [ 0.55593868  0.47170978 -0.67435458 -0.11691006]
 [ 0.46030342 -0.38505637  0.24229051 -0.76233041]
 [ 0.43242074 -0.68862695 -0.21872093  0.539413  ]]


In [20]:
v1 = evecs[:,0] # First column is the first eigenvector
print(v1)

[0.54043062 0.55593868 0.46030342 0.43242074]


In [21]:
v2 = evecs[:,1] # Second column is the second eigenvector
print(v2)

[ 0.39371868  0.47170978 -0.38505637 -0.68862695]


In [22]:
v1 @ v2

-1.9227567780970495e-16

In [23]:
P = np.array([[1,1],[1,-1]])
print(P)

[[ 1  1]
 [ 1 -1]]


In [24]:
D = np.diag((3,1))
print(D)

[[3 0]
 [0 1]]


In [25]:
M = P @ D @ la.inv(P)
print(M)

[[2. 1.]
 [1. 2.]]


In [26]:
evals, evecs = la.eig(M)
print(evals)

[3.+0.j 1.+0.j]


In [27]:
print(evecs)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [28]:
Pinv = la.inv(P)

In [29]:
k = 20

In [30]:
%%timeit
result = M.copy()
for _ in range(1,k):
    result = result @ M

The slowest run took 22.13 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 25.2 µs per loop


In [31]:
%%timeit
P @ D**k @ Pinv

The slowest run took 14.26 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.36 µs per loop
