In [119]:
import numpy as np 
#importing numpy as 'np'

Generating a Numpy Array with Random Integers 


In [4]:
n1 = np.random.randint(9,999,(4,5))
n1
#n = np.array([1,2,3,4,5,6,7,8,9,10])
#print(n)

array([[685, 904, 953, 322, 220],
       [919, 890, 581, 682, 154],
       [479, 749, 146, 430, 182],
       [330,  33, 930, 405, 329]])

Creating a Numpy Array with Random Float Values 

In [109]:
n2 = np.random.uniform(9,90,[3,8])
n2
#b = np.array([15,16,17,18,19,20],dtype='f')
#print(b)

array([[61.00623473, 32.99151717, 82.36365056, 64.83039314, 85.97665935,
        22.03596134, 42.82392491, 45.39703135],
       [46.262442  , 28.94826025, 17.008214  , 74.5860076 , 41.018801  ,
        30.99864407, 36.21946347, 40.80893724],
       [41.8882586 , 46.27282087, 24.57065243, 37.72429426, 68.97633365,
        40.8597184 , 39.99579792, 20.82462527]])

Creating a Numpy Array with Randomly generated Complex Numbers

In [110]:
n3 = np.random.random(10) + np.random.random(10)*1j
n3
#a = np.array([10,20,40],dtype="complex")
#print(a)

array([0.95684921+0.36194087j, 0.38534034+0.48054872j,
       0.80468821+0.44215539j, 0.85340675+0.96173861j,
       0.56802172+0.7995005j , 0.86488822+0.41566963j,
       0.36902005+0.03253745j, 0.69961173+0.97159714j,
       0.12345621+0.3942298j , 0.68082262+0.96007271j])

Printing Shape, Dimension and Size of Numpy Arrays

In [114]:
print(n1.shape, n1.ndim, n1.size)
print(n2.shape, n2.ndim, n2.size)
print(n3.shape, n3.ndim, n3.size)

C = np.random.randint(1,100,(4,4))
print(C)
print(C.shape)
print(C.ndim)
print(C.size)

(4, 5) 2 20
(3, 8) 2 24
(10,) 1 10
[[59 79 38 30]
 [55 61 20 20]
 [33 98 59 38]
 [ 4 99 22 85]]
(4, 4)
2
16


In [83]:
type(n1)
#type(n2)

numpy.ndarray

In [56]:
A = np.arange(16)
print(A)
print(A.shape)
print(A.reshape(2,8))
print(A.reshape(4,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Addition of Two Matrices

In [89]:
a = np.random.randint(1,100,(4,5))
b = np.random.randint(1,100,(4,5))
print("A =\n",a)
print("\nB =\n",b)
print("\nA+B =\n",a+b)
#np.add(a,b)

A =
 [[66  3  4 30 88]
 [65 23 88 32 34]
 [69 61 85 93 37]
 [36 36 77  9 47]]

B =
 [[20 31 94 31 30]
 [31 95 72 14 94]
 [26 84 62 76 59]
 [53 60 37 74 86]]

A+B =
 [[ 86  34  98  61 118]
 [ 96 118 160  46 128]
 [ 95 145 147 169  96]
 [ 89  96 114  83 133]]


Transpose of a Matrix

In [96]:
print(a)
print("\nTranspose of A =\n",a.T)
#print(a.transpose())
print("\nDouble Tranpose of A = A\n",(a.T).T)

[[66  3  4 30 88]
 [65 23 88 32 34]
 [69 61 85 93 37]
 [36 36 77  9 47]]

Transpose of A =
 [[66 65 69 36]
 [ 3 23 61 36]
 [ 4 88 85 77]
 [30 32 93  9]
 [88 34 37 47]]

Double Tranpose of A = A
 [[66  3  4 30 88]
 [65 23 88 32 34]
 [69 61 85 93 37]
 [36 36 77  9 47]]


Dot Product

In [33]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
np.dot(m1,m2)

array([[19, 22],
       [43, 50]])

Element wise Multiplication

In [115]:
np.multiply(55,2)
x1 = np.arange(9).reshape(3,3)
x2 = np.arange(3)
print("X1 =\n",x1)
print("\nX2 =\n",x2)
print("\nElement wise Multiplication =\n",np.multiply(x1,x2))
#print(x1*x2)

X1 =
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

X2 =
 [0 1 2]

Element wise Multiplication =
 [[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]]
[[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]]


Accessing Matrix Elements - Rows and Columns

In [62]:
z = np.arange(16).reshape(4,4)
print(z)
print(z[0,1]) #Element - First Row Second Column
print(z[1,3]) #Element - Second Row Fourth Column
print(z[-1,-1]) #Element - Last Row Last Column

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
1
7
15


In [66]:
z1 = np.arange(27).reshape(3,3,3)
print(z1)
print(z1[0,1,2]) #Third Element of Second Array of First Array

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
5


Slicing 

In [80]:
p = np.random.randint(10,200,(5,5))
print(p)
print(p[2:,2:])
p1 = np.random.randint(10,200,(5,5))
print(p1)
print(p1[:-2,:-2])
p2 = np.arange(10).reshape(2,5)
print(p2)
print(p2[1,1:4])
#print(p2[0:2,2])

[[102  18  48  70  91]
 [ 11  72  97  75 189]
 [ 27  67 161 181  60]
 [120 111  57 101  61]
 [ 81 122 148 109  85]]
[[161 181  60]
 [ 57 101  61]
 [148 109  85]]
[[171 184 111 146 159]
 [141 151  53 176 154]
 [ 31 197 139 112 180]
 [ 97  77  78  41 158]
 [ 36 145 140  81 145]]
[[171 184 111]
 [141 151  53]
 [ 31 197 139]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[6 7 8]


In [79]:
z1 = np.arange(10)
print(z1)
print(z1[4:])
#print(z1[:4])
#print(z1[-3:-1])
#print(z1[1:5:2])
#print(z1[::2])

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]


Reversing

In [87]:
R = np.random.randint(1,30,(4,4))
print(R)
R = R[::-1]
print(R)
R1 = np.array([1,2,3,4,5,6,7])
R1 = R1[::-1]
print(R1)

[[12 29  4 21]
 [16  9 20 15]
 [18  9  7  9]
 [11 18 27  1]]
[[11 18 27  1]
 [18  9  7  9]
 [16  9 20 15]
 [12 29  4 21]]
[7 6 5 4 3 2 1]


Downloading data through URLs and importing into Numpy Arrays

In [105]:
import csv
from numpy import genfromtxt
N = genfromtxt('https://ndownloader.figshare.com/files/12707792', delimiter=',')
print(type(N))
print(N)
print(N[1])

<class 'numpy.ndarray'>
[[ 1.07  0.44  1.5   0.2   3.2   1.18  0.09  1.44  1.52  2.44  0.78  0.02]
 [ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16  2.24  0.29  0.5 ]]
[ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16  2.24  0.29  0.5 ]
